### ISSUE TITLE
Wrong target path resolution when vhost is not mapped to root

### ISSUE THREAD

**Issue by hjelmevold** [enonic/app-rewrite#350]
Steps to reproduce:

1. XP 7.8.2
2. Rewrite Manager 1.1.4 => valid license and `com.enonic.app.rewrite.cfg` contains `enabled=true`
3. Superhero Blog => publish the site tree in Content Studio
4. Map Superhero site to path `/site` (see Note 1 below)
5. Create rule in Rewrite Manager: 
    * Virtualhost: b
    * Temporary Redirect
    * Source path: /x/y
    * Target path: /posts/featured-image
6. Spoof the site in /etc/hosts file: `127.0.0.1    my.domain`
7. New incognito/private browser window
    * http://my.domain:8080/site shows the site root, as expected
    * **BUG:** http://my.domain:8080/site/x/y redirects to http://my.domain:8080/site/x/site/posts/featured-image (should have redirected to http://my.domain:8080/site/posts/featured-image )

If site is mapped to `/` instead of to `/site`, the redirect works as expected.

**Note 1:** Contents of com.enonic.xp.web.vhost.cfg:
```
enabled = true
mapping.a.host = localhost
mapping.a.source = /
mapping.a.target = /
mapping.a.idProvider.system = default
mapping.b.host = my.domain
mapping.b.source = /site
mapping.b.target = /site/sample-blog/master/superhero
```

**Comment by anatol-sialitski** [comment]
Hi @hjelmevold,
Could you please  share with me your `com.enoni.app.rewrite.cfg`?
I guess the reason is that you have `includePattern=^/site/.*` in it.
